! =========================
! Converted to terralith:siberian_taiga
! =========================
minecraft:desert > terralith:siberian_taiga
minecraft:jungle > terralith:siberian_taiga
minecraft:mushroom_fields > terralith:siberian_taiga
minecraft:old_growth_pine_taiga > terralith:siberian_taiga
minecraft:old_growth_spruce_taiga > terralith:siberian_taiga
minecraft:savanna > terralith:siberian_taiga
minecraft:wooded_badlands > terralith:siberian_taiga
minecraft:windswept_forest > terralith:siberian_taiga

terralith:ancient_sands > terralith:siberian_taiga
terralith:amethyst_canyon > terralith:siberian_taiga
terralith:amethyst_rainforest > terralith:siberian_taiga
terralith:blooming_plateau > terralith:siberian_taiga
terralith:blooming_valley > terralith:siberian_taiga
terralith:desert_oasis > terralith:siberian_taiga
terralith:granite_cliffs > terralith:siberian_taiga
terralith:gravel_desert > terralith:siberian_taiga
terralith:highlands > terralith:siberian_taiga
terralith:mirage_isles > terralith:siberian_taiga
terralith:orchid_swamp > terralith:siberian_taiga
terralith:red_oasis > terralith:siberian_taiga
terralith:sakura_valley > terralith:siberian_taiga
terralith:scarlet_mountains > terralith:siberian_taiga
terralith:steppe > terralith:siberian_taiga
terralith:temperate_highlands > terralith:siberian_taiga
terralith:tropical_jungle > terralith:siberian_taiga
terralith:white_cliffs > terralith:forested_highlands
terralith:yosemite_cliffs > terralith:siberian_taiga



! =========================
! Converted to terralith:forested_highlands
! =========================
minecraft:badlands > terralith:forested_highlands
minecraft:birch_forest > terralith:forested_highlands
minecraft:flower_forest > terralith:forested_highlands
minecraft:meadow > terralith:forested_highlands
minecraft:plains > terralith:forested_highlands
minecraft:sparse_jungle > terralith:forested_highlands
minecraft:sunflower_plains > terralith:forested_highlands
minecraft:taiga > terralith:forested_highlands

terralith:brushland > terralith:forested_highlands
terralith:cloud_forest > terralith:forested_highlands
terralith:lavender_valley > terralith:forested_highlands
terralith:lush_desert > terralith:forested_highlands
terralith:lush_valley > terralith:forested_highlands
terralith:moonlight_valley > terralith:forested_highlands
terralith:rocky_shrubland > terralith:forested_highlands
terralith:sakura_grove > terralith:forested_highlands
terralith:yosemite_lowlands > terralith:forested_highlands
terralith:yellowstone > terralith:forested_highlands
terralith:basalt_cliffs > terralith:forested_highlands


! =========================
! Converted to terralith:shield
! =========================
minecraft:bamboo_jungle > terralith:shield
minecraft:dark_forest > terralith:shield
minecraft:eroded_badlands > terralith:shield
minecraft:forest > terralith:shield
minecraft:grove > terralith:shield
minecraft:mangrove_swamp > terralith:shield
minecraft:old_growth_birch_forest > terralith:shield
minecraft:swamp > terralith:shield

terralith:ashen_savanna > terralith:shield
terralith:arid_highlands > terralith:shield
terralith:bryce_canyon > terralith:shield
terralith:caldera > terralith:shield
terralith:desert_canyon > terralith:shield
terralith:hot_shrubland > terralith:shield
terralith:lavender_forest > terralith:shield
terralith:moonlight_grove > terralith:shield
terralith:sandstone_valley > terralith:shield
terralith:savanna_badlands > terralith:shield
terralith:savanna_slopes > terralith:shield
terralith:shrubland > terralith:shield
terralith:white_mesa > terralith:shield



! =========================
! Converted to terralith:snowy_shield
! =========================
minecraft:snowy_slopes > terralith:snowy_shield
terralith:birch_taiga > terralith:snowy_shield
terralith:ice_marsh > terralith:snowy_shield


! =========================
! Converted to terralith:siberian_grove
! =========================
terralith:cold_shrubland > terralith:siberian_grove
terralith:snowy_badlands > terralith:siberian_grove


! =========================
! Converted to terralith:snowy_maple_forest
! =========================
minecraft:frozen_peaks > terralith:snowy_maple_forest
minecraft:snowy_plains > terralith:snowy_maple_forest
minecraft:snowy_taiga > terralith:snowy_maple_forest
terralith:alpine_grove > terralith:snowy_maple_forest
terralith:frozen_cliffs > terralith:snowy_maple_forest
terralith:wintry_lowlands > terralith:snowy_maple_forest


! =========================
! Converted to terralith:wintry_forest
! =========================
minecraft:snowy_beach > terralith:wintry_forest
minecraft:ice_spikes > terralith:wintry_forest
terralith:alpine_highlands > terralith:wintry_forest


! =========================
! Converted to minecraft (odd routing)
! =========================
terralith:emerald_peaks > minecraft:stony_peaks
terralith:painted_mountains > minecraft:stony_peaks
terralith:warm_river > minecraft:river
terralith:haze_mountain > terralith:rocky_mountains


! =========================
! NULL REMOVALS
! =========================
terralith:mountain_steppe > null
terralith:skylands_winter > null
terralith:skylands_autumn > null
terralith:skylands_spring > null
terralith:skylands_summer > null
terralith:skylands > null
terralith:stony_spires > null
minecraft:crimson_forest > null
minecraft:windswept_gravelly_hills > null
minecraft:windswept_hills > null
terralith:windswept_spires > null
terralith:alpha_islands > null
minecraft:savanna_plateau > null
minecraft:windswept_savanna > null

! =========================
! OCEANS
! =========================
minecraft:deep_lukewarm_ocean > minecraft:deep_ocean
minecraft:lukewarm_ocean > minecraft:ocean
minecraft:warm_ocean > minecraft:ocean

! =========================
! LEAVE ALONE
! =========================
minecraft:beach
minecraft:cold_ocean
minecraft:deep_cold_ocean
minecraft:deep_dark
minecraft:deep_frozen_ocean
minecraft:deep_ocean
minecraft:frozen_ocean
minecraft:frozen_river
minecraft:jagged_peaks
minecraft:ocean
minecraft:river
minecraft:stony_peaks
minecraft:stony_shore

terralith:forested_highlands
terralith:gravel_beach
terralith:rocky_mountains
terralith:shield
terralith:shield_clearing
terralith:siberian_grove
terralith:siberian_taiga
terralith:snowy_maple_forest
terralith:snowy_shield
terralith:valley_clearing
terralith:volcanic_crater
terralith:wintry_forest
terralith:volcanic_peaks

! =========================
! CAVES
! =========================
minecraft:dripstone_caves
minecraft:lush_caves > null

terralith:cave/andesite_caves > null
terralith:cave/crystal_caves > null
terralith:cave/deep_caves
terralith:cave/desert_caves > null
terralith:cave/diorite_caves > null
terralith:cave/fungal_caves
terralith:cave/granite_caves > null
terralith:cave/ice_caves > null
terralith:cave/infested_caves
terralith:cave/mantle_caves
terralith:cave/tuff_caves > null
terralith:cave/thermal_caves
terralith:cave/underground_jungle > null

terralith:rocky_jungle > terralith:siberian_taiga
terralith:jungle_mountains > terralith:forested_highlands
terralith:fractured_savanna > terralith:shield
