#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Apr 30 23:05:12 BST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=4
shaderPack=DREAD REBORN SHADERS - 5 - Low.zip
enableShaders=true
